### ISSUE TITLE
Marketing: YouTube - Create DEI WG Community Office Hours template

### ISSUE THREAD

**Issue by GrooveCS** [ossf/wg-bear#7]
@GrooveCS & @marcelamelara plan to work together to create a GitHub template based on the following format in #6 

How to create a [GitHub Issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository). Once we agree to the format and content of the template, @groovecs can create a PR to be added to repo. 

Below is a quick template, and please provide any suggestions or feedback to improve the template.

--- Template Start

_Title_: "<Title Here>" - DEI WG Community Office Hour - <Date>

_Body_: 

<_Heading_> 

### Summary

<_Summary_> 

### Topics Discussed

1. <_First Topic_>
1. <_Second Topic_>
1. <_Third Topic_>

### Learnings Observed

**Mentees** can ...

**Maintainers** can ...

Learn more today: Visit OpenSSF DEI Working Group - `hyperlink`

**Comment by marcelamelara** [comment]
Thanks for getting this started @GrooveCS ! Rather than having this template as an issue template, I think we could just make this template a doc in the repo called something like `YYMM-office-hours-recap-template.md`. Then the PR can be opened directly on a copy of this doc, and we avoid the extra step of opening the issue first. What do you think?

**Comment by marcelamelara** [comment]
As an example for how to do this, I'm looking at https://github.com/ossf/tac/tree/main/TI-reports
